global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"


scrape_configs:
  - job_name: Prometheus
    scrape_interval:     20s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'Prometheus'
          environment: 'Dev'

  - job_name: WebSite
    static_configs:
      - targets: ['host.docker.internal']
        labels:
          group: 'website'